version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodejs
      - MYSQL_USER=nodejs
      - MYSQL_PASSWORD=nodejs
    volumes:
      - mysql_data:/var/lib/mysql:rw
    networks:
      - aws-xray-network

networks:
  aws-xray-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local